"""Food

Revision ID: 405fa73c2018
Revises: edb7bf8b9cf2
Create Date: 2023-10-16 09:49:37.657378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405fa73c2018'
down_revision = 'edb7bf8b9cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('africanfood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('ingredients', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.drop_table('africanfood')
    # ### end Alembic commands ###
